server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qiuyangtest?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.qy.demo.demo.bean
